name: Java SmartPrinter CI

on:
  push:
    paths:
      - 'code/java/smart_printer/**'
  pull_request:
    paths:
      - 'code/java/smart_printer/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Java (Java 21)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile source files
        run: |
          mkdir -p out
          javac -cp "code/java/smart_printer/lib/*" -d out $(find code/java/smart_printer/src -name "*.java")

      - name: Compile test files
        run: |
          javac -cp "code/java/smart_printer/lib/*:out" -d out $(find code/java/smart_printer/test -name "*.java")

      - name: Save compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: out

  test:
    name: Run Tests (JUnit 4)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: out

      - name: Run SmartPrinterTest1Login
        run: java -cp "code/java/smart_printer/lib/*:out" org.junit.runner.JUnitCore printer.SmartPrinterTest1Login

      - name: Run SmartPrinterTest2StampaBNMCDC
        run: java -cp "code/java/smart_printer/lib/*:out" org.junit.runner.JUnitCore printer.SmartPrinterTest2StampaBNMCDC

      - name: Run SmartPrinterTest3StampaCOLMCDC
        run: java -cp "code/java/smart_printer/lib/*:out" org.junit.runner.JUnitCore printer.SmartPrinterTest3StampaCOLMCDC

      - name: Run SmartPrinterTest4ScansioneMCDC
        run: java -cp "code/java/smart_printer/lib/*:out" org.junit.runner.JUnitCore printer.SmartPrinterTest4ScansioneMCDC

      - name: Run SmartPrinterTest5InUsoErrore
        run: java -cp "code/java/smart_printer/lib/*:out" org.junit.runner.JUnitCore printer.SmartPrinterTest5InUsoErrore
